using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BabySittingCoop.Migrations
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.261
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.datacontract.org/2004/07/CliqueDetector")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.datacontract.org/2004/07/CliqueDetector", IsNullable = false)]
    public partial class ArrayOfBabySittingTransaction
    {

        private ArrayOfBabySittingTransactionBabySittingTransaction[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BabySittingTransaction")]
        public ArrayOfBabySittingTransactionBabySittingTransaction[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.datacontract.org/2004/07/CliqueDetector")]
    public partial class ArrayOfBabySittingTransactionBabySittingTransaction
    {

        private string childrenWatchedField;

        private string durationField;

        private string sittingProviderIdField;

        private string sittingReceiverIdField;

        private ArrayOfBabySittingTransactionBabySittingTransactionStartedAtUtc[] startedAtUtcField;

        /// <remarks/>
        public string ChildrenWatched
        {
            get
            {
                return this.childrenWatchedField;
            }
            set
            {
                this.childrenWatchedField = value;
            }
        }

        /// <remarks/>
        public string Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        public string SittingProviderId
        {
            get
            {
                return this.sittingProviderIdField;
            }
            set
            {
                this.sittingProviderIdField = value;
            }
        }

        /// <remarks/>
        public string SittingReceiverId
        {
            get
            {
                return this.sittingReceiverIdField;
            }
            set
            {
                this.sittingReceiverIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StartedAtUtc")]
        public ArrayOfBabySittingTransactionBabySittingTransactionStartedAtUtc[] StartedAtUtc
        {
            get
            {
                return this.startedAtUtcField;
            }
            set
            {
                this.startedAtUtcField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.datacontract.org/2004/07/CliqueDetector")]
    public partial class ArrayOfBabySittingTransactionBabySittingTransactionStartedAtUtc
    {

        private string dateTimeField;

        private string offsetMinutesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://schemas.datacontract.org/2004/07/System")]
        public string DateTime
        {
            get
            {
                return this.dateTimeField;
            }
            set
            {
                this.dateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://schemas.datacontract.org/2004/07/System")]
        public string OffsetMinutes
        {
            get
            {
                return this.offsetMinutesField;
            }
            set
            {
                this.offsetMinutesField = value;
            }
        }
    }

}
